name: Build By Angular App

on:
  push:
    branches: [ main ]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Node Js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 22.X
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: npm run build

      - name: Upload Build on Artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: angular-build
          path: dist/my-app/
         
