name: Build By Angular App

on:
  push:
    branches: [ main ]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest
    # concurrency concept is that when multiple comments push at same time they create the build of latest comment and ignore the the previous all of that
    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Node Js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 22.X
      # cache concept use in this line they store the vendor etc in cache for next build
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: npm run build

      # Artifacts basically save a build of our broject in the define destination for deployments
      - name: Upload Build on Artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: angular-build
          path: dist/auto-build-github-workflow/
         
